# Generated by Django 5.2 on 2025-05-27 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=128)),
                ('door_no', models.CharField(blank=True, max_length=64, null=True)),
                ('latitude', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.CharField(blank=True, max_length=64, null=True)),
                ('address_number', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=256, null=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=64, null=True)),
                ('locality', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=256, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_modified_by', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_date', models.DateField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=128)),
                ('business_service', models.CharField(max_length=128)),
                ('business_id', models.CharField(max_length=128)),
                ('module_name', models.CharField(max_length=128)),
                ('action', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('assignees', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('last_modified_by', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherApplicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('user_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('pan', models.CharField(blank=True, max_length=16, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('alt_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('pwd_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('otp_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, to='birth_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='FatherApplicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('user_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan', models.CharField(blank=True, max_length=16, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('alt_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('pwd_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('otp_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, to='birth_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='BirthRegistrationApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=128)),
                ('application_number', models.CharField(max_length=128, unique=True)),
                ('baby_first_name', models.CharField(max_length=128)),
                ('baby_last_name', models.CharField(blank=True, max_length=128)),
                ('doctor_name', models.CharField(max_length=128)),
                ('hospital_name', models.CharField(max_length=128)),
                ('place_of_birth', models.CharField(max_length=128)),
                ('time_of_birth', models.BigIntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birth_app.address')),
                ('audit_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birth_app.auditdetails')),
                ('father_of_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birth_app.fatherapplicant')),
                ('mother_of_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birth_app.motherapplicant')),
                ('workflow', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birth_app.workflow')),
            ],
        ),
    ]
