# Generated by Django 5.2 on 2025-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistrationApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=128)),
                ('application_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('baby_first_name', models.CharField(max_length=128)),
                ('baby_last_name', models.CharField(blank=True, max_length=128)),
                ('father_of_applicant', models.CharField(max_length=128)),
                ('mother_of_applicant', models.CharField(max_length=128)),
                ('father_mobile_number', models.CharField(blank=True, max_length=15)),
                ('mother_mobile_number', models.CharField(blank=True, max_length=15)),
                ('doctor_name', models.CharField(blank=True, max_length=128)),
                ('hospital_name', models.CharField(blank=True, max_length=128)),
                ('place_of_birth', models.CharField(blank=True, max_length=128)),
                ('time_of_birth', models.BigIntegerField()),
                ('address', models.JSONField(blank=True, null=True)),
                ('applicant_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='NEW', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
